module.exports = {
  apps: [
    {
      name: 'yemenstack-whatsapp-engine',
      script: 'src/index.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        ENGINE_NAME: 'yemenstack-whatsapp-engine',
        ENGINE_POLL_INTERVAL_MS: '10000',
        LARAVEL_BASE_URL: 'http://127.0.0.1:8000',
        ENGINE_API_TOKEN: '',
        ENABLE_REAL_WHATSAPP_SEND: 'false',
        WHATSAPP_SEND_LIMIT: '1',
        WHATSAPP_TEST_RECIPIENT: '',
        WHATSAPP_SESSION_ID: 'directives_whatsapp',
        WHATSAPP_CHROME_PATH: '',
        WHATSAPP_HEADLESS: 'true',
        WHATSAPP_QR_TERMINAL_SMALL: 'true',
        WHATSAPP_RESTART_DELAY_MS: '3000',
        WHATSAPP_RESTART_TIMEOUT_MS: '60000',
        WHATSAPP_MAX_RESTART_ATTEMPTS: '3',
      },
    },
  ],
};